modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="poil"
version="1.0.0"
displayName="poil"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="FinnT, MCreator"

[[dependencies.poil]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



